### ISSUE TITLE
Allow to customize colors / pick a predefined theme

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/vis-network#3]
Current implementation do not allow to customize the network colors and we don't have any abstraction to pick a given predefined theme (for example black vs white theme). Current colors could be considered as `black` theme.

Colors are currently defined as CONSTANTS here:
https://github.com/NodeSecure/vis-network/blob/37aa9e83265ee7cce5589f184aa032365207eb40/src/constants.js#L2-L9

How current colors render on a white background:
![image](https://user-images.githubusercontent.com/4438263/168472938-7235e3e5-68c9-400e-a2a2-019005c07fe4.png)

So the main goal is to allow better customization and also predefined themes that could go well on black or white background.

**Comment by im-codebreaker** [comment]
Should we consider to have different themes wrapped in COLORS constant ? Maybe something like below : 

```js
export const COLORS = Object.freeze({
  DARK: {
    MAIN: '#01579B',
    INDIRECT: 'rgba(100, 200, 200, 1)',
    WARN: 'rgba(210, 115, 115, 1)',
    NORMAL: 'rgba(150, 200, 200, 1)',
    SELECTED: 'rgba(170, 100, 200, 1)',
    TRS: 'rgba(150, 150, 150, 0.02)',
  },
  LIGHT: {
    MAIN: '#01579B',
    INDIRECT: 'rgba(100, 200, 200, 1)',
    WARN: 'rgba(210, 115, 115, 1)',
    NORMAL: 'rgba(150, 200, 200, 1)',
    SELECTED: 'rgba(170, 100, 200, 1)',
    TRS: 'rgba(150, 150, 150, 0.02)',
  },
});
```

Constrast issues can be solved by increasing alpha value to 1 so we could easily have maybe more than 2 themes.

![Screenshot 2022-05-18 at 20-05-02 NodeSecure vis-network demo](https://user-images.githubusercontent.com/53506859/169115896-4553cd0e-211b-4d2b-9df2-8dd322188b25.png)

**Comment by fraxken** [comment]
@im-codebreaker for fixed themes that's a good idea yes.

But it could be also cool to be able to redefine them with an options payload when we instanciate the NodeSecureNetwork class.

```js
new NodeSecureNetwork(secureDataSet, {
  theme: "LIGHT",
  colors: {
    INDIRECT: ""
  }
});
```
