### ISSUE TITLE
Allow to customize node font color in THEME

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/vis-network#9]
Current theme only allow to update the background color of the Node. However in LIGHT Theme it would be cool to also be able to update the font color for a dark one (for example).

Font color is customizable like the background color:
```js
allNodes[connectedNodes[id]].color = this.colors.CONNECTED;
allNodes[connectedNodes[id]].font.color = "#000";
```

I guess a restructuration of COLORS constants is necessary:
```js
SELECTED: {
  color: "#673AB7",
  font: {
    color: "#000"
  }
}
```

I think vis.js allow something like this:
```js
allNodes[connectedNodes[id]].setOptions(this.colors.SELECTED);
```

**Comment by PierreDemailly** [comment]
I'm on it
